// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOIUnpOUb5JU5tFkl_YA3P0_iogaoOcyA',
    appId: '1:575475444349:web:13d50abef2fce9b9481f14',
    messagingSenderId: '575475444349',
    projectId: 'chattingapp-91b79',
    authDomain: 'chattingapp-91b79.firebaseapp.com',
    storageBucket: 'chattingapp-91b79.appspot.com',
    measurementId: 'G-ZV9QFF8KYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0GEChN-OWqFaHV_uK2KjZXEzhAV8gjZI',
    appId: '1:575475444349:android:b147253ef4b47680481f14',
    messagingSenderId: '575475444349',
    projectId: 'chattingapp-91b79',
    storageBucket: 'chattingapp-91b79.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj_ZVIX-ZOSMix4XFShJU1h0twas4_UDg',
    appId: '1:575475444349:ios:ba27672058deeeec481f14',
    messagingSenderId: '575475444349',
    projectId: 'chattingapp-91b79',
    storageBucket: 'chattingapp-91b79.appspot.com',
    iosBundleId: 'com.example.appc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj_ZVIX-ZOSMix4XFShJU1h0twas4_UDg',
    appId: '1:575475444349:ios:ba27672058deeeec481f14',
    messagingSenderId: '575475444349',
    projectId: 'chattingapp-91b79',
    storageBucket: 'chattingapp-91b79.appspot.com',
    iosBundleId: 'com.example.appc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOIUnpOUb5JU5tFkl_YA3P0_iogaoOcyA',
    appId: '1:575475444349:web:632d73f2dff0816b481f14',
    messagingSenderId: '575475444349',
    projectId: 'chattingapp-91b79',
    authDomain: 'chattingapp-91b79.firebaseapp.com',
    storageBucket: 'chattingapp-91b79.appspot.com',
    measurementId: 'G-RC85NMH99N',
  );
}
